version: '3.8'

services:
  ai-help-bot:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - KNOWLEDGE_GRAPH_PATH=/app/data/knowledge_graph.json
      - VECTOR_DB_PATH=/app/data/chroma_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - STREAMLIT_PORT=8501
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-help-bot
    restart: unless-stopped
    profiles:
      - production

volumes:
  data:
    driver: local