apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosdac-api
  namespace: mosdac
  labels:
    app: mosdac-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mosdac-api
  template:
    metadata:
      labels:
        app: mosdac-api
    spec:
      containers:
      - name: api
        image: mosdac-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: mosdac-config
        - secretRef:
            name: mosdac-secrets
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mosdac-api-service
  namespace: mosdac
spec:
  selector:
    app: mosdac-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP